apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::668094363898:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::668094363898:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-26T14:31:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4159"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6f1fbd7d-0ae8-4a4a-90dc-7debe888b881
