apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::668094363898:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-P0YTC6JVLF9O
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::668094363898:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-27T15:54:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "856"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: feeb182c-e677-468a-ba55-a79336892b75
